version: '3'
services: 
    app:
        container_name: docker-api-mongo-express
        restart: always
        build: .
        ports: 
            - '8080:80'
        links:
            - mongo
    mongo:
        container_name: mongo2
        image: mongo
        ports: 
            - '27018:27017'