version: '3'
services: 
    app:
        container_name: docker-api-mongo-express
        restart: always
        build: .
        ports: 
            - '2222:2222'
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
       